config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'

    root 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	 
 
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
   <div class="navbar-wrapper">
    <div class="container">

      <nav class="navbar navbar-inverse navbar-static-top text-center">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= pages_index_path %>"><strong> Your <sup>Logo</sup> </strong> </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
             <li><a href="#">About</a></li>          
             <li><a href="#">Services</a></li>
             <li><a href="#">contact Us</a></li>

             <% if user_signed_in? %>

             <li><a href="<%= edit_user_registration_path %>">Welcome, 
              <%= current_user.email  %> </a></li>

              <li><a href="<%= destroy_user_session_path %>" data-method="delete"> Log out </a></li>

              <% else  %>
              <li><a href="<%= new_user_registration_path %>">create Account</a></li>

              <li><a href="<%= new_user_session_path %>">Sign In</a></li>
              <% end %>  

            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FancyApp</title>

  <meta name="viewport" content="width=device-width, initial-scale=1"> 

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="notice_wrapper">
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% elsif alert %>  
    <p class="alert"><%= alert %></p>
    <% end %>   
  </div>


  <%= render 'layouts/navbar' %>

  <%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="container">
	<div class="row row-centered">
		<div class="col-md-8 col-centered">


			<h1>Notificaciones en devise con Jquery y SCSS </h1>
			<p><strong>Repo en Github:  <a href="https://github.com/dgattoni/deviseNotification">https://github.com/dgattoni/deviseNotification</a></strong> </p>


			<p>
				A todos nos ha pasado que cuando construimos nuestras aplicaciones, por lo general  enfocamos toda nuestra energía y tiempo en las funcionalidad core y  muchas veces olvidas o dejas para última hora esos pequeños -pero no menos importantes- detalles que mejoran la experiencia del usuario cuando interactúa con la aplicación.

				El objetivo del tutorial es  darle un estilo más "elegante" a las notificaciones y alerts de Devise con SCSS y la archi famosa librería de Javascript: Jquery.
			</p>



		</div>
	</div>
</div>